language: go
arch:
  - amd64
  - ppc64le

go:
  - tip
  - 1.15.x
  - 1.14.x
  - 1.13.x
  - 1.12.x
  - 1.11.x
  - 1.10.x

# let us have pretty, fast Docker-based Travis workers!
sudo: false

install:
  - go get -d ./...

script:
  - go test -v ./...
  - go vet ./...
